---
- hosts: '{{ hosts }}'
  remote_user: alfresco
  tasks:
  - include_tasks: tasks/doCopyGlobalProperties.yml
  - include_tasks: tasks/doCopyTomcatConfig.yml
  - include_tasks: tasks/doCopyShareConfig.yml
  - include_tasks: tasks/doCopyAlfrescoConfig.yml
